---
title: "Masters Project"
author: "Moses Omopekunola"
date: "2024-12-14"
output: html_document
---

Raters Section
```{r setup, include=FALSE}
setwd("C:/Users/OMOPEKUNOLA MOSES O/Desktop/Stat_Psy 2")
library(readxl)
library(TAM)
library(irr)
library(psych)
library(concordance)
library(rio)
library(tidyverse)
library(psych)
library(CTT)
library(ggplot2)
library(openxlsx)
library(corrplot)
library(Hmisc)
library(sirt)
library(ShinyItemAnalysis)
library(mirt)
```

CTT
```{r}
ct <- rio::import('data.xlsx')

ct<- ct %>% select(-c(Studt_Id))

key <- c('D', 'B', 'C', 'C', 'B', 'B', 'C', 'C', 'D', 'C', 'D', 'D', 	'B',
         'A', 'A', 'C',	'D', 'C', 'A', 'B',	'C', 'A', 'B', 'A', 'C', 'C', 'B', 'A', 'D', 'C', 'D', 'B', 'D', 'A', 'A', 'A', 'D',
         'B', 'A', 'B') 
key
```

Score items
```{r}
scores_ct <- score(ct,key, output.scored=TRUE)  #score the answers
scores_ct$score    #Total score
scores_ct$scored    #score for each task
scored_df <- data.frame(scored = scores_ct$scored) # store score as dataframe
#write.xlsx(scored_df_short, file = "Phy_Mock2.xlsx", rowNames = FALSE) # save score as excel file
```


Descriptive Statistics

```{r}
hist(scores_ct$score) # histogram 
psych::describe(scores_ct$score)
psych::describe(scores_ct$scored)

ch <- itemAnalysis(scores_ct$scored,NA.Delete=T,hardFlag=.15, pBisFlag=.2) # If NA.Delete=TRUE (the default) records are deleted listwise if there are missing responses. 
ch
ch$itemReport
ch$alpha
ch$scaleMean
mean(ch$itemReport$itemMean)
sd(ch$itemReport$itemMean)
```

```{r}
# Assuming `scores_ct$score` is your data column
# Create bins for the score ranges
bins <- cut(scores_ct$score, breaks = c(-Inf, 20, 25, 30, Inf), 
            labels = c("Below 20", "20 & above", "25 & above", "30 & above"))

# Calculate the frequencies
freq <- table(bins)

# Convert frequencies into a data frame for plotting
freq_df <- as.data.frame(freq)
colnames(freq_df) <- c("Score_Range", "Frequency")

# Calculate percentages
freq_df$Percentage <- round((freq_df$Frequency / sum(freq_df$Frequency)) * 100, 1)



# Create the bar plot
ggplot(freq_df, aes(x = Score_Range, y = Frequency, fill = Score_Range)) +
  geom_bar(stat = "identity", width = 0.2) +
  geom_text(aes(label = paste0(Frequency, " (", Percentage, "%)")), 
           hjust = -0.3, color = "red", fontface = "bold", size = 2) + 
  scale_fill_manual(values = c("blue", "blue", "blue", "blue")) +
  labs(title = "Distribution of Scores", 
       x = "Score Range", 
       y = "Frequency") +
  coord_flip() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5))

```


CTT SEM, Reliability

```{r}
SD <- ch$scaleSD
alpha <- ch$alpha
SEM <- SD*(sqrt(1-alpha))
SEM

```

Distractor Analysis
```{r}
ct <- na.omit(ct)#take out the NAs
distractorAnalysis(ct,key=key)
dist <-as.data.frame(distractorAnalysis(ct,key=key)) 
write.xlsx(dist, file = "Distrator.xlsx", rowNames = FALSE)
```



```{r}
plotDistractorAnalysis(Data = ct, key = key)
```

```{r}
plotDistractorAnalysis(Data = ct, key = key, item = 30)
```
```{r}
plotDistractorAnalysis(Data = ct, key = key, item = 36)
```






ICC
```{r}
cttICC(scores_ct$score, scores_ct$scored[,1], colTheme="dukes", cex=1.5) # item 1
cttICC(scores_ct$score, scores_ct$scored[,9], colTheme="dukes", cex=1.5) # item 9
cttICC(scores_ct$score, scores_ct$scored[,31], colTheme="cavaliers", cex=1.5) # item 31
cttICC(scores_ct$score, scores_ct$scored[,40], colTheme="spartans", cex=1.5) # item  40
```

Discrimination plot
```{r}
items <- ch$itemReport[,1:3]

ggplot(items,
       aes(itemName , pBis )) +
  geom_point() 

items$itemName <- factor(items$itemName, levels = items$itemName)

ggplot(items,
       aes(itemName , pBis )) +
  geom_segment(aes(y = 0, yend = pBis,x = itemName, xend = itemName), color = "#69b3a2")+
  geom_point(shape=21, color="black", fill="#69b3a2", size=5) +#
  geom_hline(yintercept=0.1,linetype="dashed", color = "gray", size=1.3)+#
  labs(title = "Discrimination") +#
  labs(x= "Item Number", y = "Discrimination")+
  theme_light() +
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
```

Difficulty plot

```{r}
ggplot(items,
       aes(itemName , itemMean )) +
  geom_segment(aes(y = 0, yend = itemMean,x = itemName, xend = itemName), color = "#69b3a2")+
  geom_point(shape=21, color="black", fill="#69b3a2", size=5) +
  geom_hline(yintercept=0.1,linetype="dashed", color = "gray", size=1.3)+
  geom_hline(yintercept=0.9, linetype="dashed", color = "gray", size=1.3)+
  labs(title = "Difficulty") +
  labs(x= "Item Number", y = "Difficulty")+
  theme_light() +
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())

```

IRT Framework

1PL
```{r}
model1pl = tam.mml(scored_df, irtmodel="1PL") 
summary(model1pl)
```

```{r}
#Item difficulties
model1pl$xsi

#Persons

ID<-model1pl$person$pid
raw<-model1pl$person$score
eapteta<-model1pl$person$EAP
eapsd<-model1pl$person$SD.EAP
scores1PL<-cbind.data.frame(ID,raw,eapteta,eapsd)
```

```{r}
Abil<-tam.wle(model1pl)
Per_abil<-Abil$theta
head(Per_abil<-Abil$theta)
hist(Abil$theta)
#hist(model1pl$person$EAP)
#cor(Abil$theta,model1pl$person$EAP)
```

Item fit
```{r}
fit_item1 <- msq.itemfit(model1pl) 
fit_item1
summary(fit_item1)
#Plots
plot(model1pl)

#Map
library(WrightMap)
# fit Rasch model
mod1 <- TAM::tam.mml(resp=scored_df)
# Wright map
IRT.WrightMap( mod1 )
IRT.WrightMap( mod1, show.thr.lab=FALSE, label.items=c(1:40), label.items.rows=3)

#Reliabilities
model1pl$EAP.rel
```


2PL
```{r}
model2pl = tam.mml.2pl(scored_df)
summary(model2pl)
mean(model2pl$person)
```

Item fit
```{r}
fit_item2 = IRT.itemfit(model2pl) 
fit_item2
```

```{r}
tam.modelfit(model2pl)$stat.MADaQ3 

```

ICC
```{r}
plot(model2pl)
```





```{r}
fit_item2 = IRT.itemfit(model2pl) 
fit_item2
```

```{r}
tam.modelfit(model2pl)$stat.MADaQ3 

Abil2<-tam.wle(model2pl)
hist(Abil2$theta)

```

```{r}
fit_item2 <- msq.itemfit(model2pl)
summary(fit_item2)
```


```{r}
plot(model2pl)
```




```{r}
anova(model1pl, model2pl)
```

```{r}
ct <- import("Phy_Mock.xlsx")

ct <- ct %>% select(-c(Studt_Id)) # Remove the student_Id column
```

```{r}
mod_1pl <- mirt(ct, 1, itemtype = 'Rasch') 
mod_2pl <- mirt(ct, 1, itemtype = '2PL')  

```


```{r}
M2(mod_1pl)
M2(mod_2pl)

```

```{r}
scored_df_short <- scored_df %>% select(-c(scored.Itm_7,scored.Itm_11,scored.Itm_31, scored.Itm_20,scored.Itm_31, scored.Itm_36))

```

```{r}
hist(scores_ct$score) # histogram 
psych::describe(scored_df_short)
psych::describe(scores_ct$scored)
```

```{r}
model2pl <- tam.mml.2pl(scored_df_short)
modelpl <- tam.mml(scored_df_short)
mean(modelpl$item$M)
modelpl$item$M
sd(modelpl$item$M)
min(modelpl$item$M)
max(modelpl$item$M)
summary(model2pl)
summary(modelpl)
anova(modelpl,model2pl)
```

```{r}
#Map
library(WrightMap)
# fit Rasch model
mod1 <- TAM::tam.mml(resp=scored_df)
# Wright map
IRT.WrightMap( mod1 )
IRT.WrightMap( mod1, show.thr.lab=FALSE, label.items=c(1:35), label.items.rows=3)

```

